server {
    listen 8000;
    server_name _;
    # client_body_buffer_size 6M;
    client_max_body_size 20M;
    root /web;
    location /images/ {
        alias /project/images/;
    }
    location / {
        proxy_pass http://app:8080;
    }
}
